### PR TITLE
Switch to Nyx version 2.0.0-beta

### PR DESCRIPTION
**Pull request by ChristopherRabotin**
This change switches the Eclipse computation to 2.0.0-beta, with ANISE as a backend.

The main question I have is whether the user should provide the Almanac for the `Solver` structure. The [Almanac](https://docs.rs/anise/latest/anise/almanac/struct.Almanac.html) contains the planetary data and solar system data needed for all of the computations. Hence, it may be useful for the user to provide that depending on their use case, even though in theory, everyone's definition of Earth is the same. If all one needs to do is change the gravitational parameter, then that can be done directly with methods on the [Frame])(https://docs.rs/anise/latest/anise/frames/struct.Frame.html) object.

In the case of the eclipse computation, we actually need to provide [tri-axial ellipsoid](https://docs.rs/anise/latest/anise/structure/planetocentric/ellipsoid/struct.Ellipsoid.html) information to define the shape of the object. But worry not! This data is available in the `pck08.pca` (and `pck11.pca`) files that are in the ANISE repo or on the Nyx cloud. The `MetaFile` structure will automatically download the provided URL if the data does not exist in the user's local temporary directory, or if the CRC of that file does not match the version that is downloaded.

### CODE REVIEW

**Comment by gwbres** [comment]
Awesome, thank you for the effort !

> The main question I have is whether the user should provide the Almanac

It is problematic to me to require internet acces on first deployment.
It's okay to require it during build time. But for me this prevents embedded / hardened environments.
It can also make things more complicated for new comers.

Why is this file (or a more simplistic option) not simply shipped with the library ? especially considering they are hosted as metadata in the library already (not a third party portal). 

I would recommend moving to a Cargo build script (rust code, run at compile time), or other build options, to ship the default file.

> The main question I have is whether the user should provide the Almanac for the Solver structure

To me, this is the only final option. Having maybe an optional input overriden by a default solution.
It is the only solution when targetting ultimate precision, using the latest almanac.
We will also means to provide daily Almanac from RINEX/V4 files, so that would be our entry point

For actual behavior and tests, refer to the PR in RINEX

**Comment by ChristopherRabotin** [comment]
> Why is this file (or a more simplistic option) not simply shipped with the library ? especially considering they are hosted as metadata in the library already (not a third party portal).
One of the common problems in my industry is checking the results of another software. To support this, most software I use allows users to configure the input files, including the planetary ephemeris data (for example, NASA Goddard and NASA JPL don't exactly agree on what is the mass of the Earth that should be used, and this is configured in a PCK file).

I understand your use case. I'll propose using `rust-embed` which is how I handled this in the previous versions of Nyx.

**Comment by gwbres** [comment]
I don't have permission to push git-lfs on this fork so you will have to do it yourself.
Although I disagree this is not the correct location for these files, they should come with ANISE

**Comment by ChristopherRabotin** [comment]
Ok! Once ANISE 0.4 is published in an hour (after dinner), I will update this PR so that it uses the `embed_ephem` crate feature of ANISE. That feature embeds the de440s.bsp and pck11.pca files into the executable such that you don't need to load or maintain external data, or download it from the internet at runtime.

**Comment by gwbres** [comment]
Sounds good. I'm starting to upgrade, but if I understand correctly, the problem is Nyx is not aligned to 4.0.0-alpha, it seems to be the last one

**Comment by ChristopherRabotin** [comment]
Yes, that's right, Nyx still need to be released, and I'll work on that in the coming days too. By the weekend, all three packages will have a release.

**Comment by gwbres** [comment]
Hello, could we get a Nyx branch that uses the same hifitime version as the others ? we do not need a release

**Comment by ChristopherRabotin** [comment]
Hi. Yes, the master branch uses 4.0.0-alpha, and used anise 0.4.0, which
also uses 4.0.0-alpha.

**Comment by gwbres** [comment]
Thank you I did not catch that! ; )

**Comment by ChristopherRabotin** [comment]
You can now use [`2.0.0-rc`](https://github.com/nyx-space/nyx/releases/tag/2.0.0-rc) ;-)

**Comment by gwbres** [comment]
I'm OK with merging these new features, even without https://github.com/nyx-space/anise/issues/269 as a temporary phase, whatever its duration. Once this topic is "resolved" it will naturaly modify the behavior and requirements

**Comment by gwbres** [comment]
merging this, i'm done not being able to work in my own libraries

**Review by gwbres — APPROVED** [review]

**Pull request merged**
